# Generated by Django 3.2.5 on 2021-09-10 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usefull_decorators', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='films',
            name='price',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
