# Generated by Django 3.2.5 on 2021-08-23 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
