# Generated by Django 3.2.5 on 2021-08-24 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0003_auto_20210823_2132'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
    ]
