# Generated by Django 3.2.5 on 2021-08-24 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0004_citycount'),
    ]

    operations = [
        migrations.AddField(
            model_name='citycount',
            name='town',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_one.country'),
            preserve_default=False,
        ),
    ]
