# Generated by Django 3.2.5 on 2021-08-26 16:07

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0006_film'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='film',
            managers=[
                ('search_with_filter', django.db.models.manager.Manager()),
            ],
        ),
    ]
