# Generated by Django 3.2.5 on 2021-08-28 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0007_alter_film_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='film',
            managers=[
            ],
        ),
    ]
