# Generated by Django 3.1 on 2020-12-05 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fortest', '0002_auto_20201205_1437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='belonging',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='borrowed',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='friend',
            name='owner',
        ),
    ]
