# Generated by Django 3.1 on 2020-12-24 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('razpad', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Recepies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Simples',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('group', models.ForeignKey(default=1, limit_choices_to={'razpad': False}, on_delete=django.db.models.deletion.CASCADE, related_name='simples', to='products.grops')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('group', models.ForeignKey(default=2, limit_choices_to={'razpad': True}, on_delete=django.db.models.deletion.CASCADE, related_name='recepies', to='products.grops')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.simples')),
                ('recepies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.recepies')),
            ],
        ),
        migrations.AddField(
            model_name='recepies',
            name='ingredients',
            field=models.ManyToManyField(through='products.RecipeIngredient', to='products.Simples'),
        ),
    ]
