# Generated by Django 3.1 on 2020-12-24 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_simples_razpad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simples',
            name='razpad',
        ),
    ]
