# Generated by Django 3.1 on 2020-12-24 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_recipeingredient_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recepies',
            name='ingredients',
            field=models.ManyToManyField(db_index=True, through='products.RecipeIngredient', to='products.Simples'),
        ),
    ]
