# Generated by Django 3.1 on 2020-12-24 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_simples_razpad'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='simples',
            options={'ordering': ['pk']},
        ),
        migrations.AlterField(
            model_name='simples',
            name='group',
            field=models.ForeignKey(limit_choices_to={'razpad': False}, on_delete=django.db.models.deletion.CASCADE, related_name='simples', to='products.grops'),
        ),
    ]
