# Generated by Django 3.1 on 2020-12-24 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20201224_1352'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recepies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('group', models.ForeignKey(limit_choices_to={'grpup': True}, on_delete=django.db.models.deletion.CASCADE, related_name='recepies', to='products.grops')),
                ('simple', models.ManyToManyField(to='products.Simples')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
    ]
