# Generated by Django 3.1 on 2020-12-24 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_recepies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recepies',
            name='group',
            field=models.ForeignKey(limit_choices_to={'razpad': True}, on_delete=django.db.models.deletion.CASCADE, related_name='recepies', to='products.grops'),
        ),
        migrations.AlterField(
            model_name='recepies',
            name='simple',
            field=models.ManyToManyField(related_name='recepies', to='products.Simples'),
        ),
    ]
